#! /bin/sh

bspc monitor eDP1 -d III IV V VI VII VIII IX X
#bspc monitor DVI-D-0 -d III IV V VI VII VIII IX X
bspc monitor HDMI1 -d I II

desktop_config() {
	bspc config $1 $2
	for M in $(bspc query -M); do
		bspc config -m $M $1 $2
	done
}

desktop_config border_width			4.0	
desktop_config window_gap			15

bspc config window_gap			30	
bspc config top_padding			40
bspc config right_padding		0	
bspc config bottom_padding		0
bspc config left_padding		0
bspc config split_ratio			0.50

bspc config borderless_monocle		true
bspc config gapless_monocle				true
bspc config focus_by_distance			true
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#282a2e"
bspc config active_border_color		"#f3f3f3"
bspc config focused_border_color	"#5f819d"
bspc config presel_border_color		"#f3f3f3"
bspc config urgent_border_color		"#f3f3f3"
bspc config focused_locked_border_color	"#f3f3f3"

bspc rule -a urxvt floating=off
#bspc rule -a Chromium desktop=^2
bspc rule -a feh floating=on
bspc rule -a nemo floating=on

# set background
#feh --bg-scale ~/Pictures/bspwm-wallpapers/ghost_nebula.jpg
/$HOME/bin/random-wallpaper

# rules
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a feh floating=on

# autostart

$HOME/bin/panelecho | lemonbar -g 3200x40+0+0 -p -f "Cantarell-Regular:size=12" -f "FontAwesome:size=9" -f "cambria:size=13"
dropbox start
