#!/bin/sh

primary_monitor="$(xrandr | grep -i primary | sed -E 's/([^ ]*).*/\1/g')"
bspc monitor "$primary_monitor" -d 1 2 3 4 5 6 7 8 9

desktop_config() {
  bspc config $1 $2
  for M in $(bspc query -M); do
    bspc config -m $M $1 $2
  done
}

desktop_config border_width		2.0
desktop_config window_gap		15

bspc config window_gap                  0
bspc config top_padding                 0
bspc config bottom_padding              0
bspc config right_padding		0
bspc config left_padding		0

bspc config split_ratio			0.50

bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config focus_follows_pointer	false

bpc rule -a urxvt floating=off
bspc rule -a feh floating=on
bspc rule -a nemo floating=on

# rules
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a feh floating=on
