#!/bin/bash

set -eu

# Script for installing things I use which isn't available in either pacman,
# nix or from AUR for arch based distros.

VIM_EDITOR="nvim"

echo "Installing yay"
yay --version || { \
  tmpdir="$(mktemp -d)"
  git clone https://aur.archlinux.org/yay.git "$tmpdir"
  cd "$tmpdir"
  git checkout "2ecf033ddea1c85b5a61588d1ed865da00fed09d"
  makepkg --noconfirm -si
  cd -
  rm -rf "$tmpdir"
}

echo "Installing fonts"
install-fonts

echo "Installing plugged to $VIM_EDITOR"
plug_vim_file="$HOME/.config/$VIM_EDITOR/autoload/plug.vim"
[[ -f "$plug_vim_file" ]] || \
  curl -fLo ~/".config/$VIM_EDITOR/autoload/plug.vim" \
  --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing solarixed neovim theme"
[[ -f ~/".config/nvim/colors/solarized.vim" ]] || { \
  color_dir="$HOME/.config/nvim/colors" ;
  mkdir -p "$color_dir" ; \
  tmp=$(mktemp -d) ; \
  cd "$tmp" ; \
  git clone https://github.com/altercation/vim-colors-solarized.git ; \
  cp ./*/colors/solarized.vim "$color_dir" ;
  cd - ;
}

[[ -d "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim" ]] || \
  git clone --depth 1 https://github.com/wbthomason/packer.nvim \
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim

echo "Installing vim plugins with plug"
# Run :PlugInstall in vim non-interactively to install plugins
# Does currently not work
# vim +'PackerInstall --sync' +qa

echo "Install kubectl krew modules"
for krew_plugin in ns ctx ; do
  if ! kubectl "$krew_plugin" --help &> /dev/null ; then
    kubectl krew install "$krew_plugin"
  fi
done
