#!/bin/bash

set -eu

VIM_EDITOR="nvim"

echo "Installing fonts"
install-fonts

echo "Installing plugged to $VIM_EDITOR"
plug_vim_file="$HOME/.config/$VIM_EDITOR/autoload/plug.vim"
[[ -f "$plug_vim_file" ]] || \
  curl -fLo ~/".config/$VIM_EDITOR/autoload/plug.vim" \
  --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[[ -d "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim" ]] || \
  git clone --depth 1 https://github.com/wbthomason/packer.nvim \
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim

echo "Installing vim plugins with plug"
# Run :PlugInstall in vim non-interactively to install plugins
vim +'PackerInstall --sync' +qa

echo "Install kubectl krew modules"
for krew_plugin in ns ctx ; do
  if ! kubectl "$krew_plugin" --help &> /dev/null ; then
    kubectl krew install "$krew_plugin"
  fi
done
